23 permission conflict x
aberezkin/codecolla pull request #29
Opened 2017-12-10 05:54 UTC by J-CITY

-X-conflict
-fix cursors
-fix bug in peerjs
-dummy ctrl-z
-synchronize crdt when peer connect

2017-12-10 13:16 UTC, aberezkin commented
Опять много изменений в одной ветке. 

По хорошему это можно было разделить на 3 PR

1. Return cursors
2. Resolve x conflict
3. Send init text

2017-12-10 13:49 UTC, aberezkin requested changes

2017-12-10 13:49 UTC, aberezkin commented on src/actions/index.js
> +export const GET_ALL_TEXT = 'GET ALL TEXT';
Зачем это?

2017-12-10 13:49 UTC, aberezkin commented on src/components/Editor/Editor.jsx
> +        this.props.moveCursor(this.editor.getCursorPosition());
TODO нужно убрать.

2017-12-10 13:49 UTC, aberezkin commented on src/middleware/cursor.js
> +            //next(action);
Нужно удалить.

2017-12-10 13:49 UTC, aberezkin commented on src/middleware/peer.js
> +var PeerID = '';
Вроде как `PeerID` больше нигде не используется, т.к. теперь id хранится в `store`. Нужно удалить.

2017-12-10 13:49 UTC, aberezkin commented on src/middleware/peer.js
> +            //dispatch(broadcastActions(ChangeEvent.getAddPeerEvent(connection.peer)));
Почему ты это закоментировал?

2017-12-10 13:49 UTC, aberezkin commented on src/middleware/peer.js
> +    dispatch(broadcastActions(ChangeEvent.getAddPeerEvent(connection.peer)));
Совсем не понимаю

1. Почему это перешло сюда?
2. Ты тут совсем не правильно используешь `broadcastActions`.

2017-12-10 13:49 UTC, aberezkin commented on src/middleware/peer.js
> +                console.log(conn.peer);
Мусор. Верни как было.

2017-12-10 13:49 UTC, aberezkin commented on src/middleware/peer.js
> +        case BROADCAST_DATA_FOR_PEER:
Вообще логичнее было бы название `BROADCAST_ACTION_TO_PEER`.

2017-12-10 13:49 UTC, aberezkin commented on src/middleware/peer.js
> +            store.getState().peers.connections.forEach(conn => {
1. Это бы лучше смотрелось как
```
store.getState().peers.connections
    .find(conn => conn.peer === action.payload.id)
    .send(JSON.stringify(action.payload.text));
```
2. Мы же договорились по сети отсылать исключительно reduxовские `actions` почему ты шлешь какой-то текст?

2017-12-10 13:49 UTC, aberezkin commented on src/middleware/text.js
> +            console.log('$$$$$$$$$$\n');
Хватит засирать консоль бессмысленными логами! Оттестировал что-то, убери за собой.

2017-12-10 13:49 UTC, aberezkin commented on src/middleware/text.js
> +            if (action.payload.atom.time <= store.getState().text.get(action.payload.line).time) {
`store.getState().text.get(action.payload.line).time` можно вынести в переменную (а лучше `const`), т.к ты ей пользуешься многократно.

2017-12-10 13:49 UTC, aberezkin commented on src/middleware/text.js
> +            if (action.payload.atom.time <= store.getState().text.get(action.payload.line).time) {
Даже `store.getState().text.get(action.payload.line)` можно вынести.

2017-12-10 13:49 UTC, aberezkin commented on src/middleware/text.js
> +            if (action.payload.atom.time <= store.getState().text.get(action.payload.line).time) {
И потом сразу ее диспатчить

2017-12-10 13:49 UTC, aberezkin commented on src/middleware/text.js
> +            } else if (action.payload.atom.time === store.getState().text.get(action.payload.line).time) {
Когда у тебя стоит два `if` подряд можно воспользоваться оператором `&&`

2017-12-10 13:49 UTC, aberezkin commented on src/middleware/text.js
> +            let sendArr = store.getState().text.map(atom => {
В функцию, которую ты передаешь аргументом в `map` вторым аргументом передается индекс, так что `i` тут не нужен.

2017-12-10 13:49 UTC, aberezkin commented on src/middleware/text.js
> +                return {
Почему не сделать так:
```
{
    type: SET_ATOMS,
    payload: List<Atom>()
}
```

2017-12-10 13:49 UTC, aberezkin commented on src/middleware/peer.js
> +            store.getState().peers.connections.forEach(conn => {
А, текст и есть `action` по сути, но у тебя высший экшн называется общо (`BROADCAST_DATA_FOR_PEER`) а делает одно конкретное действие (пересылает текст). Нужно либо называть его конкретно, либо делать интерфейс более обший (не `action.payload.text` а `action.payload.broadcastedAction` к примеру).

Спойлер: второй вариант лучше, т.к. позволит переиспользовать этот экшн в других целях.

2017-12-10 13:49 UTC, aberezkin commented on src/middleware/text.js
> +                return {
Т.е. пересылать просто сразу список весь в одном экшене, куча маленьких экшенов вызовет кучу циклов диспатча. Все равно в этот момент нас не волнует там всякие `time` и тому подобное.

2017-12-10 13:49 UTC, aberezkin commented on src/reducers/cursor.js
> +    console.log('STATE: ', state);
Опять мусор в консоль...

2017-12-10 13:49 UTC, aberezkin commented on src/reducers/peer.js
> +function connectionReducer(state = [], action) {
connectionS - у нас же тут массив!

2017-12-10 13:49 UTC, aberezkin commented on src/reducers/text.js
> +        case GET_ALL_TEXT:
Этот кейс **НИЧЕМ** не отличается от `SET_LINE`, тогда зачем платить дважды?

2017-12-10 13:49 UTC, aberezkin commented
Исправь конфликт еще.

2017-12-10 15:17 UTC, aberezkin commented on src/middleware/text.js
> +                return {
Тем более для этого уже есть `SET_TEXT`

2017-12-11 06:54 UTC, J-CITY commented on src/middleware/peer.js
> +            //dispatch(broadcastActions(ChangeEvent.getAddPeerEvent(connection.peer)));
Иначе, он ту ошибку выдаёт.

2017-12-11 07:23 UTC, merged