Menubar component
aberezkin/codecolla pull request #42
Opened 2017-12-15 20:14 UTC by kofes

Resolve #18

2017-12-20 15:13 UTC, aberezkin requested changes

2017-12-20 15:13 UTC, aberezkin commented on src/components/StatusBar/StatusBar.jsx
> +        if (this.props.isVisible)
Может лучше не `if`ом а просто в `style` написать что-то вроде

`style={visibility: this.props.isVisible ? 'visible' : 'hidden', ...this.props.style}` ?

2017-12-20 15:13 UTC, aberezkin commented on src/components/App/App.jsx
> +            width -= 250;
Эти все манипуляции с высотой и шириной оч жестко выглядят, от них нельзя избавиться?

2017-12-20 15:13 UTC, aberezkin commented on src/components/App/App.jsx
> +                <div className={'wrapper'} style={{...this.style.wrapper, height: height+'px'}}>
По стилю предпочтительно использовать шаблонные строки, т.е. 

    height: `${height}px`

2017-12-20 15:13 UTC, aberezkin commented on src/components/App/App.jsx
> +                            height={height+'px'}
В этих местах соответсвенно тоже

2017-12-20 15:13 UTC, aberezkin commented on src/components/Chat/Chat.jsx
> +            <div className={`${CHAT_CLASSNAME}`} tabIndex="0" style={(!this.props.isVisible)? {visibility: 'hidden', display: 'none'} : {}}>
Вот тут ты как раз сделал через `style`. Я думаю точно так же можно сделать в `StatusBar`

2017-12-20 15:13 UTC, aberezkin commented on src/components/Menu/Menu.jsx
> +                            <MenuItem title={'New'} command={'menu-new'}/>
Тут `command`ы по хорошему тоже в именнованные константы вынести.

2017-12-20 15:13 UTC, aberezkin commented on src/components/MenuBar/MenuItem/MenuItem.jsx
> +    bindCloseHandlers() {
Тут наверное имеется ввиду `bindClickHandlers()`

2017-12-20 15:13 UTC, aberezkin commented on src/components/MenuBar/MenuItem/MenuItem.jsx
> +    unbindCloseHandlers() {
Тут тоже

2017-12-20 15:13 UTC, aberezkin commented on src/components/MenuBar/SubMenu/SubMenu.jsx
> +    }
Почему ты не ставишь пустые строки между функциями в классе? Это же удобно!

2017-12-20 15:14 UTC, aberezkin commented
По хорошему еще на компоненты тесты написать. Хотя бы парочку.

2017-12-22 13:11 UTC, aberezkin commented on src/components/Chat/Chat.jsx
> +            <div className={`${CHAT_CLASSNAME}`} tabIndex="0"
`CHAT_CLASSNAME` просто не сработает чтоли???

2017-12-22 13:13 UTC, kofes commented on src/components/Chat/Chat.jsx
> +            <div className={`${CHAT_CLASSNAME}`} tabIndex="0"
ахахах

2017-12-22 13:22 UTC, kofes commented on src/components/MenuBar/MenuItem/MenuItem.jsx
> +    bindCloseHandlers() {
функция handle нажатие вне меню, после чего меню will close

2017-12-22 13:57 UTC, aberezkin approved these changes

2017-12-22 13:59 UTC, merged