41 compilebox integration
aberezkin/codecolla pull request #53
Opened 2017-12-30 01:55 UTC by leetim

Готово, хотя автоматическое тестирование большой проблема.

2018-01-04 02:46 UTC, aberezkin requested changes

2018-01-04 02:46 UTC, aberezkin commented on src/actions/index.js
> +export function sendCode(langid, text) {
Мне кажется эту функцию можно протестировать.

2018-01-04 02:46 UTC, aberezkin commented on src/middleware/index.js
> +const middlewares = [peers, chat, text, multi, compileCode, fetchMiddleware];
Тут лучше, чтобы multi был в именно в конце. Этот `middleware` обрабатывает массивы, так что если какой-то из `middleware` после него диспатчит массив, он не обработается.

И наверное стоит написать коммент об этом.

2018-01-04 02:46 UTC, aberezkin commented on src/middleware/compile-code.js
> +            const addMessageAction = addMessage(createMessage('Code is sending'));
> Code is sent

2018-01-04 02:46 UTC, aberezkin commented on src/middleware/compile-code.js
> +const getLanguage = (actionType) => {
Наверное было бы удобно сделать `Map`, в котором бы были доступны `id` языков по их названию. У нас в state есть язык, который сейчас выбран в качестве основного в редакторе и таким образом можно было бы автоматически определять, какой id при компиляции отправлять в `CompileBox`.

2018-01-04 02:46 UTC, aberezkin commented on src/reducers/chat.js
> +            console.log(action.value.errors);
Уберай за собой после дебага :)

2018-01-12 13:55 UTC, leetim commented
Поправил! Смотри)

2018-01-13 00:36 UTC, aberezkin commented
Код хороший. На паре сегодня посмотрим как это работает :)

2018-01-13 00:36 UTC, aberezkin submitted a review, later dismissed

2018-01-13 13:19 UTC, aberezkin approved these changes

2018-01-13 13:20 UTC, merged