Add fullscreen mode
aberezkin/codecolla pull request #87
Opened 2018-01-23 11:41 UTC by J-CITY

Add fullscreen mode

2018-01-23 13:22 UTC, aberezkin requested changes

2018-01-23 13:22 UTC, aberezkin commented on src/middleware/fullscreen.js
> +const textMiddleware = store => next => action => {
Почему это называется `textMiddleware`??

2018-01-23 13:26 UTC, J-CITY commented on src/middleware/fullscreen.js
> +const textMiddleware = store => next => action => {
ну да, надо fullscreenMiddleware

2018-01-24 01:41 UTC, aberezkin commented
Баг, когда заходишь в Fullscreen мышкой, а выходишь по `F11` галка в меню не убирается

2018-01-27 01:46 UTC, aberezkin approved these changes

2018-01-27 01:46 UTC, merged